spring:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      maxActive: 20
      maxIdle: 5
      minIdle: 2
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      username: root
      password: cc1016
      initial-size: 5
      min-idle: 2
      max-active: 10
      max-wait: 60000
      url: jdbc:mysql://127.0.0.1:3306/management?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
server:
  port: 8999
mybatis:
  mapper-locations: classpath:mapper/*.xml